/* Chabaquito V1: lógica pura. Solo un backend autorizado puede acreditar evidencias. */
(function (root) {
  'use strict';
  const TYPES = Object.freeze(['confirmed_visit', 'self_visit', 'digital_objective']);
  const COLLECTIONS = Object.freeze({ profiles:'chabaquitoExplorerProfiles', evidence:'evidence', xpEvents:'xpEvents', adventures:'adventures', leaderboard:'chabaquitoPublicRanking' });
  const LEVELS = Object.freeze([
    Object.freeze({minXp:0,name:'Viajero Curioso'}),Object.freeze({minXp:500,name:'Caminante de Loja'}),Object.freeze({minXp:1500,name:'Aventurero Lojano'}),Object.freeze({minXp:3000,name:'Explorador de Loja'}),Object.freeze({minXp:5000,name:'Conocedor de Loja'}),Object.freeze({minXp:8000,name:'Guardián de Loja'}),Object.freeze({minXp:12000,name:'Maestro Explorador'}),Object.freeze({minXp:20000,name:'Leyenda de Loja'})
  ]);
  const POINTS=Object.freeze({POINT_A:Object.freeze({id:'POINT_A',active:false,latitude:null,longitude:null,radiusMeters:null,maxAccuracyMeters:null}),ESTABLISHMENT_B:Object.freeze({id:'ESTABLISHMENT_B',active:false,placeId:null}),POINT_C:Object.freeze({id:'POINT_C',active:false,latitude:null,longitude:null,radiusMeters:null,maxAccuracyMeters:null})});
  const PILOT=Object.freeze({id:'tras-las-huellas-de-chabaquito',title:'Tras las huellas de Chabaquito',objectives:Object.freeze([Object.freeze({id:'descubre',type:'digital_objective',proofId:'pilot_discover',xp:50}),Object.freeze({id:'cultura',type:'digital_objective',proofId:'pilot_culture',xp:50}),Object.freeze({id:'autonoma-uno',type:'self_visit',proofId:'pilot_self_one',pointId:'POINT_A',xp:50}),Object.freeze({id:'con-encargado',type:'confirmed_visit',proofId:null,pointId:'ESTABLISHMENT_B',xp:50}),Object.freeze({id:'autonoma-dos',type:'self_visit',proofId:'pilot_self_two',pointId:'POINT_C',xp:50})]),completionXp:250,badge:Object.freeze({id:'amigo-de-chabaquito',title:'Amigo de Chabaquito'}),levelThresholds:Object.freeze(LEVELS.map(level=>level.minXp))});
  function identifier(value,label){if(typeof value!=='string'||!/^[a-zA-Z0-9_-]{1,128}$/.test(value))throw new Error(`${label} no válido.`);return value;}
  function evidenceKey(evidence){return `${identifier(evidence.type,'Tipo')}:${identifier(evidence.sourceId,'Origen')}`;}
  function normalizeEvidence(input){const type=identifier(input?.type,'Tipo');if(!TYPES.includes(type))throw new Error('Tipo de evidencia desconocido.');const sourceId=identifier(input.sourceId,'Origen');const proofId=input.proofId==null?null:identifier(input.proofId,'Objetivo');if(type!=='confirmed_visit'&&!proofId)throw new Error('El objetivo es obligatorio.');if(!['validated','reversed'].includes(input.status))throw new Error('Estado no válido.');const verifiedAt=Number(input.verifiedAt);if(!Number.isSafeInteger(verifiedAt)||verifiedAt<=0)throw new Error('Fecha validada no válida.');return Object.freeze({type,sourceId,proofId,status:input.status,verifiedAt});}
  function evaluateAdventure(adventure,evidenceList){const objectives=adventure?.objectives;if(!adventure||!Array.isArray(objectives)||!objectives.length||new Set(objectives.map(o=>o.id)).size!==objectives.length||!Number.isSafeInteger(adventure.completionXp)||adventure.completionXp<0||!adventure.badge?.id||!objectives.every(o=>TYPES.includes(o.type)&&Number.isSafeInteger(o.xp)&&o.xp>=0))throw new Error('Configuración de aventura no válida.');const latest=new Map();for(const raw of evidenceList||[]){if(raw?.scope==='tourism_discovery')continue;const evidence=normalizeEvidence(raw),key=evidenceKey(evidence),previous=latest.get(key);if(!previous||evidence.verifiedAt>previous.verifiedAt||(evidence.verifiedAt===previous.verifiedAt&&evidence.status==='reversed'))latest.set(key,evidence);}const used=new Set(),completedObjectives=[],xpEvents=[],completionTimes=new Map();const unlocks={descubre:[],cultura:['descubre'],'autonoma-uno':['cultura'],'con-encargado':['cultura'],'autonoma-dos':['autonoma-uno','con-encargado']};for(const objective of objectives){const prerequisites=unlocks[objective.id]||[];if(!prerequisites.every(id=>completionTimes.has(id)))continue;const unlockAt=prerequisites.length?Math.max(...prerequisites.map(id=>completionTimes.get(id))):0;const matching=[...latest.values()].filter(e=>e.status==='validated'&&e.type===objective.type&&e.verifiedAt>=unlockAt&&(objective.proofId==null||objective.proofId===e.proofId)&&!used.has(evidenceKey(e))).sort((a,b)=>a.verifiedAt-b.verifiedAt||evidenceKey(a).localeCompare(evidenceKey(b)));const evidence=matching[0];if(!evidence)continue;const key=evidenceKey(evidence);used.add(key);completedObjectives.push(objective.id);completionTimes.set(objective.id,evidence.verifiedAt);xpEvents.push({id:`${adventure.id}:${objective.id}`,evidenceKey:key,xp:objective.xp});}const completed=completedObjectives.length===objectives.length;if(completed)xpEvents.push({id:`${adventure.id}:completion`,evidenceKey:null,xp:adventure.completionXp});const xp=xpEvents.reduce((total,event)=>total+event.xp,0);if(!Number.isSafeInteger(xp))throw new Error('XP fuera de rango.');const availableObjectives=objectives.filter(objective=>!completedObjectives.includes(objective.id)&&(unlocks[objective.id]||[]).every(id=>completedObjectives.includes(id))).map(objective=>objective.id);return Object.freeze({completed,completedObjectives,availableObjectives,xpEvents,xp,badgeIds:completed?[adventure.badge.id]:[]});}
  function levelForXp(xp,thresholds=PILOT.levelThresholds){if(!Number.isSafeInteger(xp)||xp<0||!Array.isArray(thresholds)||thresholds[0]!==0||thresholds.some((n,i)=>!Number.isSafeInteger(n)||n<0||(i>0&&n<=thresholds[i-1])))throw new Error('XP o niveles no válidos.');return thresholds.filter(n=>xp>=n).length;}
  function reconcileXp(previousEvents,nextEvents){const previous=new Map(previousEvents.map(e=>[e.id,e])),next=new Map(nextEvents.map(e=>[e.id,e]));if(previous.size!==previousEvents.length||next.size!==nextEvents.length)throw new Error('Eventos XP duplicados.');return{grant:[...next.values()].filter(e=>!previous.has(e.id)||previous.get(e.id).xp!==e.xp||previous.get(e.id).evidenceKey!==e.evidenceKey),revoke:[...previous.values()].filter(e=>!next.has(e.id)||next.get(e.id).xp!==e.xp||next.get(e.id).evidenceKey!==e.evidenceKey)};}
  function publicRankingEntry(profile){if(profile?.participateInRanking!==true)return null;const alias=String(profile.publicAlias||'').trim();if(!alias||alias.length>40||/[<>\x00-\x1f]/.test(alias))throw new Error('Alias público no válido.');const xp=profile.validatedXp,avatar=profile.publicAvatar||null;if(avatar!==null&&(typeof avatar!=='string'||!/^https:\/\/[a-z0-9.-]+\//i.test(avatar)||avatar.length>1000))throw new Error('Avatar público no válido.');return Object.freeze({alias,avatar,level:levelForXp(xp,profile.levelThresholds||PILOT.levelThresholds),xp,badgeIds:(profile.publicBadgeIds||[]).filter(id=>typeof id==='string'&&/^[a-zA-Z0-9_-]{1,128}$/.test(id)).slice(0,3)});}
  const api=Object.freeze({TYPES,COLLECTIONS,LEVELS,POINTS,PILOT,evidenceKey,normalizeEvidence,evaluateAdventure,levelForXp,reconcileXp,publicRankingEntry});if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.VisitaLojaChabaquitoV1Core=api;
})(typeof window!=='undefined'?window:null);
