'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {service}=require('./loyalty-notification-service'),{key}=require('./loyalty-points-service');
function fixture(){
 const records=new Map(),writes=[];let tail=Promise.resolve(),time=Date.parse('2026-10-10T18:00:00Z'),failCreate=false;
 const clone=v=>v===undefined?undefined:structuredClone(v);
 function snapshot(ref){const value=clone(records.get(ref.path));return {id:ref.id,exists:value!==undefined,data:()=>clone(value)}}
 function collection(path){return {doc(id){const ref={id,path:path+'/'+id,get:async()=>snapshot(ref),collection:name=>collection(path+'/'+id+'/'+name)};return ref},where:(f,op,v)=>query(path,[[f,v]]),orderBy:(f,dir)=>query(path,[],f,dir)}}
 function query(path,filters=[],order='__name__',direction='asc',cursor=null,limit=Infinity){return {isQuery:true,where:(f,op,v)=>query(path,[...filters,[f,v]],order,direction,cursor,limit),orderBy:(f,dir='asc')=>query(path,filters,f,dir,cursor,limit),startAfter:v=>query(path,filters,order,direction,v,limit),limit:n=>query(path,filters,order,direction,cursor,n),async get(){const docs=[...records].filter(([p,v])=>p.startsWith(path+'/')&&p.slice(path.length+1).indexOf('/')===-1&&filters.every(([f,x])=>v[f]===x)).map(([p])=>snapshot({id:p.slice(path.length+1),path:p})).sort((a,b)=>{const x=order==='__name__'?a.id:a.data()[order],y=order==='__name__'?b.id:b.data()[order];return(x<y?-1:x>y?1:0)*(direction==='desc'?-1:1)}).filter(s=>!cursor||s.id>cursor).slice(0,limit);return {docs,size:docs.length}}}}
 const db={collection,async runTransaction(fn){let release;const previous=tail;tail=new Promise(r=>release=r);await previous;const pending=[];let writing=false;
  const tx={async get(ref){if(writing)throw Error('read after write');return ref.isQuery?ref.get():snapshot(ref)},set(ref,value){writing=true;pending.push([ref,value,false])},update(ref,value){writing=true;if(!records.has(ref.path))throw Error('missing');pending.push([ref,value,true])},create(ref,value){writing=true;if(failCreate)throw Error('injected failure');if(records.has(ref.path))throw Error('already exists');pending.push([ref,value,false])}};
  try{const result=await fn(tx);for(const [ref,value,merge]of pending){records.set(ref.path,merge?{...records.get(ref.path),...clone(value)}:clone(value));writes.push(ref.path)}return result}finally{release()}
 }};
 const put=(collection,id,data)=>records.set(collection+'/'+id,clone(data));
 put('settings','loyaltyNotificationsV88',{enabled:true});put('settings','loyaltyV83',{enabled:true});put('locales','cafe',{title:'Café',publicationStatus:'published'});put('missionRewardMerchants','owner',{active:true,placeIds:['cafe']});
 put('loyaltyNotificationPrograms','cafe',{enabled:true,ownerCanPublish:true,batchSize:25,maxDailyDeliveries:100});
 const api=service({db,clock:()=>time}),owner={uid:'owner'},admin={uid:'admin',token:{admin:true}},customer={uid:'alice'};
 const campaign={placeId:'cafe',campaignId:'offer',title:'Café especial',message:'Te esperamos',conditions:'Una bebida',startsAt:'2026-10-10T12:00',endsAt:'2026-10-12T12:00'};
 const follower=(uid,patch={})=>put('loyaltyFollows',key(uid,'cafe'),{userId:uid,placeId:'cafe',active:true,promotions:true,consentVersion:1,...patch});
 const publish=async()=>{await api.save(owner,campaign);return api.publish(owner,{...campaign,expectedVersion:1})};
 return {api,records,writes,put,owner,admin,customer,campaign,follower,publish,setTime:t=>time=Date.parse(t),failWrites:()=>failCreate=true};
}
const error=code=>e=>e.code===code;
test('draft save enforces revision and publication permission; published content is immutable',async()=>{const f=fixture();await f.api.save(f.owner,f.campaign);await assert.rejects(f.api.save(f.owner,f.campaign),error('aborted'));f.put('loyaltyNotificationPrograms','cafe',{enabled:true,ownerCanPublish:false});await assert.rejects(f.api.publish(f.owner,{...f.campaign,expectedVersion:1}),error('permission-denied'));await f.api.publish(f.admin,{...f.campaign,expectedVersion:1});await assert.rejects(f.api.save(f.owner,{...f.campaign,expectedVersion:1}),error('failed-precondition'));});
test('delivery requires same-business promotion consent, never accepts manual recipient payloads',async()=>{const f=fixture();await f.publish();f.follower('alice');f.follower('no-consent',{promotions:false});f.follower('inactive',{active:false});f.follower('unknown-version',{consentVersion:0});f.put('loyaltyFollows',key('hotel-user','hotel'),{userId:'hotel-user',placeId:'hotel',active:true,promotions:true,consentVersion:1});const r=await f.api.dispatch(f.owner,{...f.campaign,userId:'no-consent',recipients:['no-consent']});assert.equal(r.created,1);const inbox=await f.api.inbox(f.customer,{userId:'no-consent'});assert.equal(inbox.notifications.length,1);assert.equal(inbox.notifications[0].push,false);assert.equal((await f.api.inbox({uid:'no-consent'})).notifications.length,0);});
test('retries and concurrent deliveries create one notification and debit quota once',async()=>{const f=fixture();await f.publish();f.follower('alice');const results=await Promise.all([f.api.dispatch(f.owner,f.campaign),f.api.dispatch(f.owner,f.campaign)]);assert.equal(results.reduce((n,r)=>n+r.created,0),1);const r=await f.api.dispatch(f.owner,f.campaign);assert.equal(r.created,0);assert.equal(r.alreadyDelivered,1);assert.equal(r.totalDelivered,1);const quotas=[...f.records].filter(([path])=>path.startsWith('loyaltyNotificationQuotas/'));assert.equal(quotas[0][1].delivered,1);});
test('bounded pagination reaches every consented follower without returning identities',async()=>{const f=fixture();await f.publish();for(let i=0;i<61;i++)f.follower('person-'+i);let cursor=null,total=0,batches=0;do{const result=await f.api.dispatch(f.owner,{...f.campaign,cursor});assert.ok(result.created<=25);assert.equal('recipients'in result,false);total+=result.created;cursor=result.nextCursor;batches++}while(cursor);assert.equal(total,61);assert.equal(batches,3);});
test('daily quota applies across campaigns and resets using Ecuador calendar',async()=>{const f=fixture();f.put('loyaltyNotificationPrograms','cafe',{enabled:true,ownerCanPublish:true,batchSize:1,maxDailyDeliveries:1});await f.publish();f.follower('alice');await f.api.dispatch(f.owner,f.campaign);const another={...f.campaign,campaignId:'second'};await f.api.save(f.owner,another);await f.api.publish(f.owner,{...another,expectedVersion:1});await assert.rejects(f.api.dispatch(f.owner,another),error('resource-exhausted'));f.setTime('2026-10-11T04:59:00Z');await assert.rejects(f.api.dispatch(f.owner,another),error('resource-exhausted'));f.setTime('2026-10-11T05:00:00Z');assert.equal((await f.api.dispatch(f.owner,another)).created,1);});
test('global pause and per-business pause block delivery, but allow inbox and read acknowledgments',async()=>{const f=fixture();await f.publish();f.follower('alice');await f.api.dispatch(f.owner,f.campaign);f.put('settings','loyaltyNotificationsV88',{enabled:false});await assert.rejects(f.api.dispatch(f.owner,f.campaign),error('failed-precondition'));const inbox=await f.api.inbox(f.customer);await f.api.markRead(f.customer,{notificationId:inbox.notifications[0].notificationId});await f.api.pause(f.owner,f.campaign);assert.equal((await f.api.overview(f.owner,f.campaign)).campaigns[0].status,'paused');});
test('revoked assignment, consent, follower subsystem or owner permission prevents later deliveries',async()=>{for(const reason of ['assignment','consent','followers','owner']){const f=fixture();await f.publish();f.follower('alice');if(reason==='assignment')f.put('missionRewardMerchants','owner',{active:false,placeIds:['cafe']});if(reason==='consent')f.follower('alice',{promotions:false});if(reason==='followers')f.put('settings','loyaltyV83',{enabled:false});if(reason==='owner')f.put('loyaltyNotificationPrograms','cafe',{enabled:true,ownerCanPublish:false,batchSize:25,maxDailyDeliveries:100});if(reason==='consent')assert.equal((await f.api.dispatch(f.owner,f.campaign)).created,0);else await assert.rejects(f.api.dispatch(f.owner,f.campaign),error(reason==='followers'?'failed-precondition':'permission-denied'));assert.equal((await f.api.inbox(f.customer)).notifications.length,0)}});
test('future, expired, hidden, draft and paused promotions cannot be delivered',async()=>{for(const reason of ['future','expired','hidden','draft','paused']){const f=fixture();await f.api.save(f.owner,f.campaign);if(reason!=='draft')await f.api.publish(f.owner,{...f.campaign,expectedVersion:1});if(reason==='future')f.setTime('2026-10-10T16:59:00Z');if(reason==='expired')f.setTime('2026-10-12T17:00:00Z');if(reason==='hidden')f.put('locales','cafe',{title:'Café',publicationStatus:'hidden'});if(reason==='paused')await f.api.pause(f.owner,f.campaign);f.follower('alice');await assert.rejects(f.api.dispatch(f.owner,f.campaign),error('failed-precondition'));}});
test('notification write failure rolls back quota and all recipients',async()=>{const f=fixture();await f.publish();f.follower('alice');f.follower('bob');f.failWrites();await assert.rejects(f.api.dispatch(f.owner,f.campaign));assert.equal((await f.api.inbox(f.customer)).notifications.length,0);assert.equal([...f.records.keys()].some(path=>path.startsWith('loyaltyNotificationQuotas/')),false);assert.equal((await f.api.overview(f.owner,f.campaign)).campaigns[0].deliveryCount,0);});
test('read acknowledgments use authenticated UID and remain idempotent',async()=>{const f=fixture();await f.publish();f.follower('alice');await f.api.dispatch(f.owner,f.campaign);const notificationId=(await f.api.inbox(f.customer)).notifications[0].notificationId;await assert.rejects(f.api.markRead({uid:'bob'},{notificationId,userId:'alice'}),error('not-found'));await f.api.markRead(f.customer,{notificationId});const before=f.writes.length;await f.api.markRead(f.customer,{notificationId});assert.equal(f.writes.length,before);await assert.rejects(f.api.inbox(null),error('unauthenticated'));});
test('invalid dates, oversized windows and owner attempts to lift quotas reject without writes',async()=>{const f=fixture();const before=f.writes.length;for(const patch of [{startsAt:'2026-02-30T12:00'},{endsAt:f.campaign.startsAt},{endsAt:'2026-12-10T12:00'},{title:''}])await assert.rejects(f.api.save(f.owner,{...f.campaign,...patch}),error('invalid-argument'));await assert.rejects(f.api.configure(f.owner,{placeId:'cafe',enabled:true,ownerCanPublish:true,maxDailyDeliveries:500}),error('permission-denied'));await assert.rejects(f.api.configure(f.admin,{placeId:'cafe',enabled:true,ownerCanPublish:true,maxDailyDeliveries:1,batchSize:2}),error('invalid-argument'));assert.equal(f.writes.length,before);});
