'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {service,prepareAward,prepareReversal,key,configData,rewardData}=require('./loyalty-points-service');
function fixture(){
 const records=new Map(),writes=[];let tail=Promise.resolve(),autoId=0;
 const clone=value=>{if(Array.isArray(value))return value.map(clone);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,clone(v)]));return value;};
 const snap=(ref,data=records.get(ref.path))=>({id:ref.id,exists:data!==undefined,data:()=>data===undefined?undefined:clone(data)});
 const db={collection(name){return {doc(docId){docId=docId??("auto"+(++autoId));const ref={id:docId,path:name+'/'+docId};ref.get=async()=>snap(ref);return ref;},where(field,op,value){return query(name,[[field,value]])}}},async runTransaction(fn){let release;const previous=tail;tail=new Promise(r=>release=r);await previous;let writing=false;const pending=[];
 const tx={async get(ref){if(writing)throw Error('read after write');return snap(ref);},set(ref,data){writing=true;pending.push(['set',ref,data]);},create(ref,data){writing=true;if(records.has(ref.path))throw Error('already exists');pending.push(['set',ref,data]);},update(ref,data){writing=true;if(!records.has(ref.path))throw Error('missing');pending.push(['update',ref,data]);},delete(ref){writing=true;pending.push(['delete',ref]);}};
 try{const result=await fn(tx);for(const [op,ref,data] of pending){writes.push({op,path:ref.path,data});if(op==='delete')records.delete(ref.path);else records.set(ref.path,op==='update'?{...records.get(ref.path),...data}:data);}return result;}finally{release();}
 }};
 function query(name,filters){return {where(f,op,v){return query(name,[...filters,[f,v]])},limit(n){return {...query(name,filters),get:async()=>{const docs=[...records].filter(([k,v])=>k.startsWith(name+'/')&&filters.every(([f,x])=>v[f]===x)).slice(0,n).map(([k,v])=>snap({id:k.split('/')[1]},v));return {docs,size:docs.length}}}},async get(){return this.limit(10000).get()}};}
 const put=(name,id,value)=>records.set(name+'/'+id,value),get=(name,id)=>records.get(name+'/'+id);
 put('settings','loyaltyV83',{enabled:true,maxPointsPerStamp:50});put('locales','cafe',{title:'Café'});put('locales','hotel',{title:'Hotel'});put('missionRewardMerchants','owner',{active:true,placeIds:['cafe']});put('loyaltyPointPrograms','cafe',{enabled:true,ownerCanConfigure:true,pointsPerStamp:10});
 let time=1000;const api=service({db,clock:()=>time});const customer={uid:'customer',token:{}},owner={uid:'owner',token:{}},admin={uid:'admin',token:{admin:true}};
 const award=(requestId='visit1',placeId='cafe')=>db.runTransaction(async tx=>{const plan=await prepareAward({tx,db,userId:customer.uid,placeId,requestId,now:time});plan?.apply();return plan?.amount||0;});
 const reverse=(requestId='visit1',amount=10)=>db.runTransaction(async tx=>{const plan=await prepareReversal({tx,db,visit:{userId:customer.uid,placeId:'cafe',pointsEarned:amount},requestId,now:time});plan?.apply();});
 const reward=(extra={})=>api.saveReward(owner,{placeId:'cafe',rewardId:'coffee',title:'Café de cortesía',conditions:'Un café',cost:10,stock:2,active:true,validityDays:1,...extra});
 return {db,api,put,get,writes,records,customer,owner,admin,award,reverse,reward,setTime:v=>time=v};
}
const error=code=>e=>e.code===code;
test('confirmed stamps are idempotent and separate balances by business',async()=>{const f=fixture();await f.award();await assert.rejects(f.award(),error('already-exists'));f.put('loyaltyPointPrograms','hotel',{enabled:true,pointsPerStamp:3});await f.award('visit2','hotel');assert.equal(f.get('loyaltyPointAccounts',key('customer','cafe')).balance,10);assert.equal(f.get('loyaltyPointAccounts',key('customer','hotel')).balance,3);assert.notEqual(key('a_b','c'),key('a','b_c'));});
test('disabled gate and legacy stamps never backfill points',async()=>{const f=fixture();f.put('settings','loyaltyV83',{enabled:false});assert.equal(await f.award(),0);assert.equal(f.writes.length,0);await f.reverse('legacy',0);assert.equal(f.writes.length,0);});
test('transaction rollback leaves no partial points',async()=>{const f=fixture();await assert.rejects(f.db.runTransaction(async tx=>{const p=await prepareAward({tx,db:f.db,userId:'customer',placeId:'cafe',requestId:'fail',now:1});p.apply();throw Error('stamp failed');}));assert.equal(f.writes.length,0);});
test('reversal uses original award despite rate changes and pause',async()=>{const f=fixture();await f.award();f.put('settings','loyaltyV83',{enabled:false});f.put('loyaltyPointPrograms','cafe',{pointsPerStamp:25});await f.reverse();assert.equal(f.get('loyaltyPointAccounts',key('customer','cafe')).balance,0);await assert.rejects(f.reverse(),error('failed-precondition'));});
test('redemption retry spends once and payload cannot grant balance',async()=>{const f=fixture();await f.award();await f.reward();const data={placeId:'cafe',rewardId:'coffee',requestId:'r1',userId:'owner',cost:0};const c=await f.api.redeem(f.customer,data);await f.api.redeem(f.customer,data);assert.equal(f.get('loyaltyPointAccounts',key('customer','cafe')).balance,0);assert.equal(f.get('loyaltyPointRewards',key('cafe','coffee')).issued,1);assert.equal(c.cost,10);await assert.rejects(f.api.redeem(f.customer,{...data,rewardId:'different'}),error('already-exists'));});
test('concurrent retries and limited stock prevent overspend',async()=>{const f=fixture();await f.award();await f.reward({stock:1});const outcomes=await Promise.allSettled(['one','two'].map(requestId=>f.api.redeem(f.customer,{placeId:'cafe',rewardId:'coffee',requestId})));assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.equal(f.get('loyaltyPointAccounts',key('customer','cafe')).balance,0);});
test('another customer cannot use the first customer points',async()=>{const f=fixture();await f.award();await f.reward();await assert.rejects(f.api.redeem({uid:'other'},{placeId:'cafe',rewardId:'coffee',requestId:'r1'}),error('failed-precondition'));});
test('spent stamp blocks reversal; cancel refunds once and releases stock',async()=>{const f=fixture();await f.award();await f.reward();const c=await f.api.redeem(f.customer,{placeId:'cafe',rewardId:'coffee',requestId:'r1'});await assert.rejects(f.reverse(),error('failed-precondition'));await f.api.settle(f.customer,{claimId:c.claimId,action:'cancel'});await f.api.settle(f.customer,{claimId:c.claimId,action:'cancel'});assert.equal(f.get('loyaltyPointAccounts',key('customer','cafe')).balance,10);assert.equal(f.get('loyaltyPointRewards',key('cafe','coffee')).issued,0);await f.reverse();assert.equal(f.get('loyaltyPointAccounts',key('customer','cafe')).balance,0);});
test('deliver only by assigned owner/admin; irreversible delivered state',async()=>{const f=fixture();await f.award();await f.reward();const c=await f.api.redeem(f.customer,{placeId:'cafe',rewardId:'coffee',requestId:'r1'});await assert.rejects(f.api.settle(f.customer,{claimId:c.claimId,action:'deliver'}),error('permission-denied'));await assert.rejects(f.api.settle({uid:'stranger'},{claimId:c.claimId,action:'cancel'}),error('permission-denied'));await f.api.settle(f.owner,{claimId:c.claimId,action:'deliver'});await f.api.settle(f.owner,{claimId:c.claimId,action:'deliver'});await assert.rejects(f.api.settle(f.customer,{claimId:c.claimId,action:'cancel'}),error('failed-precondition'));});
test('expired claims cannot be delivered but refund remains possible during pause',async()=>{const f=fixture();await f.award();await f.reward();const c=await f.api.redeem(f.customer,{placeId:'cafe',rewardId:'coffee',requestId:'r1'});f.setTime(86401000);await assert.rejects(f.api.settle(f.owner,{claimId:c.claimId,action:'deliver'}),error('deadline-exceeded'));f.put('settings','loyaltyV83',{enabled:false});await f.api.settle(f.customer,{claimId:c.claimId,action:'cancel'});assert.equal(f.get('loyaltyPointAccounts',key('customer','cafe')).balance,10);});
test('admin grants owner controls, owner cannot self-enable or exceed cap',async()=>{const f=fixture();f.put('loyaltyPointPrograms','cafe',{enabled:false,ownerCanConfigure:false,pointsPerStamp:10});const config={placeId:'cafe',enabled:true,ownerCanConfigure:true,pointsPerStamp:10};await assert.rejects(f.api.configure(f.owner,config),error('permission-denied'));await f.api.configure(f.admin,{...config,enabled:false});const x=await f.api.configure(f.owner,config);assert.equal(x.enabled,false);await assert.rejects(f.api.configure(f.owner,{...config,pointsPerStamp:51}),error('invalid-argument'));await assert.rejects(f.api.configure(f.owner,{...config,placeId:'hotel'}),error('permission-denied'));});
test('disabled owner can no longer edit rewards and stock cannot erase reservations',async()=>{const f=fixture();await f.award();await f.reward();await f.api.redeem(f.customer,{placeId:'cafe',rewardId:'coffee',requestId:'r1'});await assert.rejects(f.reward({stock:0}),error('failed-precondition'));f.put('missionRewardMerchants','owner',{active:false,placeIds:['cafe']});await assert.rejects(f.reward(),error('permission-denied'));});
test('follow is explicit, private, no push and revocable during pause',async()=>{const f=fixture();await f.api.follow(f.customer,{placeId:'cafe',active:true,promotions:false,birthdays:true});const value=f.get('loyaltyFollows',key('customer','cafe'));assert.equal(value.promotions,false);assert.equal(value.pushConsent,false);assert(!('email' in value));assert.equal((await f.api.overview(f.owner,{placeId:'cafe'})).followers.total,1);f.put('settings','loyaltyV83',{enabled:false});await f.api.follow(f.customer,{placeId:'cafe',active:false,promotions:true,birthdays:true});assert.equal(f.get('loyaltyFollows',key('customer','cafe')).birthdays,false);});
test('wallet reads only own business and owner overview exposes aggregates',async()=>{const f=fixture();await f.award();await f.reward();await f.api.follow(f.customer,{placeId:'cafe',active:true,promotions:true,birthdays:false});const wallet=await f.api.wallet(f.customer,{placeId:'cafe',userId:'stranger'});assert.equal(wallet.account.balance,10);assert.equal(wallet.ledger.length,1);const overview=await f.api.overview(f.owner,{placeId:'cafe'});assert.deepEqual(overview.followers,{total:1,promotions:1,birthdays:0});assert(!JSON.stringify(overview).includes('customer'));await assert.rejects(f.api.overview(f.owner,{placeId:'hotel'}),error('permission-denied'));});
test('reject malformed amounts and identity',()=>{assert.throws(()=>configData({pointsPerStamp:1.5}));assert.throws(()=>rewardData({title:'a',cost:-1}));assert.throws(()=>key('bad/path'));});
function handlers(f){const fs=require('node:fs'),vm=require('node:vm'),out={},stamp=value=>({millis:value,toMillis(){return this.millis}}),Timestamp={now:()=>stamp(Date.now()),fromMillis:stamp};class HttpsError extends Error{constructor(code,message){super(message);this.code=code}}
const context={exports:out,console,require(name){if(name==='firebase-functions/v2/https')return {onCall:(_,fn)=>fn,HttpsError};if(name==='firebase-functions/v2/firestore')return {onDocumentWritten:(_,fn)=>fn};if(name==='firebase-admin/app')return {initializeApp(){}};if(name==='firebase-admin/firestore')return {getFirestore:()=>f.db,Timestamp,FieldValue:{increment:v=>v}};if(name==='./chabaquito-v1-visit-validation')return {processValidatedVisit:async()=>{}};if(name==='./chabaquito-missions-v2-service')return {safeSyncUserMissionsV2:async()=>{}};return require(name);}};
vm.runInNewContext(fs.readFileSync(__dirname+'/index.js','utf8'),context,{filename:'index.js'});
f.put('visitCodes','v1',{status:'pending',expiresAt:stamp(Date.now()+60000),userId:'customer',placeId:'cafe'});f.put('loyaltyPrograms','cafe',{active:true,targetVisits:10,maxVisitsPerDay:3});return {out,Timestamp};}
test('actual confirm and reverse handlers integrate points in the stamp transaction',async()=>{const f=fixture(),{out}=handlers(f),req={auth:f.owner,data:{requestId:'v1'}};const result=await out.confirmLoyaltyVisit(req);assert.equal(result.pointsEarned,10);assert.equal(f.get('loyaltyVisits','v1').pointsEarned,10);assert.equal(f.get('loyaltyPointAccounts',key('customer','cafe')).balance,10);await assert.rejects(out.confirmLoyaltyVisit(req),error('failed-precondition'));await out.reverseLastLoyaltyVisit(req);assert.equal(f.get('loyaltyVisits','v1').status,'reversed');assert.equal(f.get('loyaltyPointAccounts',key('customer','cafe')).balance,0);});
test('actual confirm preserves legacy behavior when V83 is disabled',async()=>{const f=fixture(),{out}=handlers(f);f.put('settings','loyaltyV83',{enabled:false});const result=await out.confirmLoyaltyVisit({auth:f.owner,data:{requestId:'v1'}});assert.equal(result.pointsEarned,0);assert.equal(result.visitCount,1);assert.equal([...f.records.keys()].filter(k=>k.startsWith('loyaltyPointAccounts')).length,0);});
test('actual handlers reject revoked merchant and balance misuse without partial changes',async()=>{const f=fixture(),{out}=handlers(f),req={auth:f.owner,data:{requestId:'v1'}};await out.confirmLoyaltyVisit(req);await f.reward();await f.api.redeem(f.customer,{placeId:'cafe',rewardId:'coffee',requestId:'r1'});const before=f.writes.length;await assert.rejects(out.reverseLastLoyaltyVisit(req),error('failed-precondition'));assert.equal(f.writes.length,before);assert.equal(f.get('loyaltyVisits','v1').status,'confirmed');f.put('missionRewardMerchants','owner',{active:false,placeIds:['cafe']});await assert.rejects(out.reverseLastLoyaltyVisit(req),error('permission-denied'));});
test('actual callable wrapper maps service authorization and error codes',async()=>{const f=fixture(),{out}=handlers(f);await assert.rejects(out.redeemLoyaltyPoints({auth:null,data:{placeId:'cafe',rewardId:'coffee',requestId:'r1'}}),error('unauthenticated'));await assert.rejects(out.configureLoyaltyPoints({auth:f.customer,data:{placeId:'cafe',enabled:true,ownerCanConfigure:true,pointsPerStamp:10}}),error('permission-denied'));});
