"use strict";
const BASE="https://www.visitaloja.com", PROJECT="cultura-y-cuchara";
const CONFIG={
 "hoteles-en-loja":{title:"Hoteles en la provincia de Loja",description:"Explora alojamientos publicados en distintos cantones de la provincia de Loja y encuentra información para planificar tu estadía.",categories:["hotel","hoteles","hostal","hostales","hospedaje","alojamiento","alojamientos"],intro:"Descubre opciones de hospedaje en la provincia de Loja. Consulta cada ficha para conocer el establecimiento, su ubicación y sus servicios."},
 "restaurantes-en-loja":{title:"Restaurantes en la provincia de Loja",description:"Conoce restaurantes de la provincia de Loja con información y enlaces directos a sus fichas en VisitaLoja.com.",categories:["restaurante","restaurantes","restaurant","comida tipica","gastronomia","picanteria","hueca","asadero","cevicheria"],intro:"Encuentra restaurantes para disfrutar de la gastronomía de Loja y sus cantones. Revisa la información publicada por cada establecimiento."},
 "cafeterias-en-loja":{title:"Cafeterías en la provincia de Loja",description:"Descubre cafeterías y espacios para disfrutar del café en la provincia de Loja, Ecuador.",categories:["cafeteria","cafeterias","cafe","coffee shop"],intro:"Explora cafeterías de la provincia de Loja y conoce sus propuestas. Abre las fichas para descubrir más detalles."},
 "que-hacer-en-loja":{title:"Qué hacer en la provincia de Loja",description:"Explora atractivos y experiencias turísticas publicados en la provincia de Loja, Ecuador.",categories:["turismo","atractivo turistico","atractivos turisticos","experiencia turistica","experiencias turisticas","lugar turistico","sitio turistico","atractivo","naturaleza","cultura","aventura","destino turistico"],intro:"La provincia de Loja tiene múltiples destinos y experiencias por descubrir. Comienza por estos lugares publicados y consulta sus fichas para planificar tu visita."}
};
const escape=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const slug=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
function val(v){if(!v)return"";if("stringValue"in v)return v.stringValue;if("booleanValue"in v)return v.booleanValue;if("arrayValue"in v)return(v.arrayValue.values||[]).map(val);if("mapValue"in v){const o={};for(const[k,x]of Object.entries(v.mapValue.fields||{}))o[k]=val(x);return o}return""}
function match(x,c){const raw=[x.category,x.categoria,x.type,x.tipo].flatMap(v=>Array.isArray(v)?v:[v]);return raw.some(v=>c.categories.includes(slug(v).replace(/-/g," ")))}
function published(x){const statuses=[x.publicationStatus,x.status].filter(v=>v!==undefined&&v!==null&&String(v).trim()!=="").map(v=>String(v).toLowerCase());return statuses.every(v=>["published","active"].includes(v))}
async function places(fetchImpl=fetch){let token="",all=[];do{const u=new URL("https://firestore.googleapis.com/v1/projects/"+PROJECT+"/databases/(default)/documents/locales");u.searchParams.set("pageSize","300");if(token)u.searchParams.set("pageToken",token);const r=await fetchImpl(u);if(!r.ok)throw Error("Firestore "+r.status);const data=await r.json();for(const d of data.documents||[]){const x={id:decodeURIComponent(d.name.split("/").pop())};for(const[k,v]of Object.entries(d.fields||{}))x[k]=val(v);if(!published(x))continue;all.push(x)}token=data.nextPageToken||""}while(token);return all}
function render(key,items,availableKeys=[key]){const c=CONFIG[key],canonical=BASE+"/"+key,desc=c.description;const cards=items.map(x=>{const name=x.title_es||x.title||x.id,href="/parada/"+encodeURIComponent(slug(x.slug||x.title||x.id)),image=x.heroImage||x.image||(Array.isArray(x.gallery)&&x.gallery.find(g=>g&&g.img)||{}).img||"",address=x.address_es||x.address||"",summary=String(x.desc_es||x.desc||"").slice(0,180);return '<article class="card"><a href="'+escape(href)+'">'+(image?'<img loading="lazy" src="'+escape(image)+'" alt="'+escape(name)+'">':'<div class="placeholder">VISITA LOJA</div>')+'<div class="details"><h2>'+escape(name)+'</h2>'+(address?'<p class="address">'+escape(address)+'</p>':'')+(summary?'<p>'+escape(summary)+'</p>':'')+'<strong>Ver información →</strong></div></a></article>'}).join("");
const schema={"@context":"https://schema.org","@type":"CollectionPage",name:c.title,description:desc,url:canonical,mainEntity:{"@type":"ItemList",numberOfItems:items.length,itemListElement:items.map((x,i)=>({"@type":"ListItem",position:i+1,name:x.title_es||x.title||x.id,url:BASE+"/parada/"+encodeURIComponent(slug(x.slug||x.title||x.id))}))}};
return '<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="index,follow,max-image-preview:large"><title>'+escape(c.title)+' | VisitaLoja.com</title><meta name="description" content="'+escape(desc)+'"><link rel="canonical" href="'+canonical+'"><meta property="og:type" content="website"><meta property="og:site_name" content="VisitaLoja.com"><meta property="og:title" content="'+escape(c.title)+' | VisitaLoja.com"><meta property="og:description" content="'+escape(desc)+'"><meta property="og:url" content="'+canonical+'"><meta property="og:image" content="'+BASE+'/visita-loja-compartir.png"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="'+escape(c.title)+' | VisitaLoja.com"><meta name="twitter:description" content="'+escape(desc)+'"><meta name="twitter:image" content="'+BASE+'/visita-loja-compartir.png"><script type="application/ld+json">'+JSON.stringify(schema).replace(/</g,"\\u003c")+'</script><style>*{box-sizing:border-box}body{margin:0;font-family:system-ui,Arial,sans-serif;background:#f7f3ec;color:#17221c}header{background:#111b17;color:white;padding:20px max(20px,calc((100vw - 1100px)/2))}header a{color:inherit;text-decoration:none;font-weight:800}.hero{background:#142b24;color:white;padding:65px 20px}.wrap{max-width:1100px;margin:auto}.hero h1{font-size:clamp(2rem,5vw,3.5rem);margin:0 0 18px}.hero p{max-width:750px;line-height:1.7}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,270px),1fr));gap:22px;padding:36px 0 70px}.card{background:white;border:1px solid #e5dfd4;border-radius:20px;overflow:hidden;box-shadow:0 8px 20px #17221c0b}.card a{color:inherit;text-decoration:none}.card img,.placeholder{width:100%;height:190px;object-fit:cover}.placeholder{display:grid;place-items:center;background:#294c3c;color:white;font-weight:800}.details{padding:20px}.details h2{margin:0 0 12px;font-size:1.25rem}.details p{line-height:1.5;color:#52615b}.details strong{color:#bc5c16}.address{font-size:.9rem}main{padding:0 20px}nav{display:flex;gap:15px;flex-wrap:wrap;margin-top:22px}nav a{color:#c85d19}footer{padding:25px 20px;background:#111b17;color:white;text-align:center}</style></head><body><header><a href="/">📍 VISITA LOJA</a></header><section class="hero"><div class="wrap"><h1>'+escape(c.title)+'</h1><p>'+escape(c.intro)+'</p></div></section><main class="wrap"><nav aria-label="Explorar categorías">'+availableKeys.map(k=>'<a href="/'+k+'">'+escape(CONFIG[k].title)+'</a>').join("")+'</nav><div class="grid">'+cards+'</div></main><footer>Descubre la provincia de Loja · <a style="color:white" href="/">VisitaLoja.com</a></footer></body></html>'}
module.exports=async function handler(req,res){const key=String(req.query.categoria||"");if(!CONFIG[key])return res.status(404).send("Categoría no encontrada");try{const all=await places(),items=all.filter(x=>match(x,CONFIG[key])).sort((a,b)=>String(a.title||"").localeCompare(String(b.title||""),"es"));if(!items.length){res.setHeader("X-Robots-Tag","noindex");res.setHeader("Cache-Control","public, s-maxage=300");return res.status(404).send("Esta categoría todavía no tiene lugares publicados.");}res.setHeader("Content-Type","text/html; charset=utf-8");res.setHeader("Cache-Control","public, s-maxage=1800, stale-while-revalidate=3600");return res.status(200).send(render(key,items,Object.keys(CONFIG).filter(k=>all.some(x=>match(x,CONFIG[k])))))}catch(e){console.error("SEO category",e);return res.status(503).send("No se pudo cargar la categoría.")}};
module.exports._test={CONFIG,match,render,slug,published};
